GET http://localhost:5000/studentlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyMTMwNjc1NjZkYjM3YTNmMTFmMTg0OCIsInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRuWVVsMHZWUTk5V0tiVWJzYkpnV3NPNGlmNGIxbjZ6QXRHL0JaL0FsZVFzdUhCUVp5UzdCVyIsIl9fdiI6MH0sImlhdCI6MTY0NTQxNzcxOH0.LFal-su0K2E8Lo7sHoq1PxpEn-RD0sFVOefRQj8PySI
###

POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

POST http://localhost:5000/newadmin   
Content-Type: application/json

{
    
    "username": "admin",
    "password": "admin"
}

